export const data = [
    {
        id: 1, 
        placeName: 'Museum hop along Miracle Mile', 
        description: 'The collections of the Los Angeles County Museum of Art, or LACMA, are housed in a vast complex of buildings, with a modern and contemporary art-filled west campus that opened 2008 and a single-building redesign on the way. The focal point is its grand entrance, which includes Chris Burden’s photogenic installation Urban Light. LACMA shares a park with the La Brea Tar Pits and sits just across the street from the Petersen Automotive Museum and Craft Contemporary, and next to the Academy Museum of Motion Pictures.', 
        image: 'https://media.timeout.com/images/105496731/1372/1029/image.jpg', 
        source: 'https://www.timeout.com/',
        showMore: false,
    },
    {
        id: 2, 
        placeName: 'Stroll (briefly) along the stars in Hollywood', 
        description: 'For a glimpse of the stardust on which the city’s built, stroll along the Hollywood Walk of Fame, where more than 2,700 of the entertainment world’s most illustrious names are immortalized in pink terrazzo and gold lettering. For film fanatics, the famous hand and footprints at the Chinese Theatre are a requisite stop—though the tourist-choked area leaves much to be desired. Countless galas, premieres and award ceremonies have passed through over the decades and although the area isn’t nearly as glitzy as you imagined, Hollywood, unpleasant as it may be, still has its (brief) place in a visit to L.A.', 
        image: 'https://media.timeout.com/images/102424953/1372/1029/image.jpg', 
        source: 'https://www.timeout.com/',
        showMore: false,
    },
    {
        id: 3, 
        placeName: 'Venice Beach', 
        description: 'Venice Beach has long been known as the bohemian epicenter of California, and while the area gets plenty of mainstream tourists, it still boldly embraces its eccentric spirit—for better or worse. Abbot Kinney has transformed into a high-end ’hood over recent years, but the boardwalk is still a, let’s say, unique place for people watching, with radical pamphleteers, skateboarders and body builders all making their presence known (if you’re simply after a picturesque stretch of beach, we suggest venturing to Santa Monica or Malibu instead). Grab lunch at the Fig Tree before browsing the shelves at Small World Books. Make sure to stray from the boardwalk and stroll along the Venice Canals, too.', 
        image: 'https://media.timeout.com/images/105494794/1372/1029/image.jpg', 
        source: 'https://www.timeout.com/',
        showMore: false,
    },
    {
        id: 4, 
        placeName: 'Disneyland', 
        description: 'You’re never too old for Disneyland. This legendary theme park overflows with brilliant things to do, spread over numerous themed lands—including Star Wars: Galaxy’s Edge and Avengers Campus—and the adjacent California Adventure. After making sure you’re up to speed best food, stroll down Main Street USA for a taste of early-19th-century America, trek Westwards at Frontierland and soak up the music of New Orleans Square. Of course, there are dozens of rides too, including the epic Indiana Jones Adventure and, across the way in California Adventure, the uplifting Soarin’.', 
        image: 'https://media.timeout.com/images/103937453/1372/1029/image.jpg', 
        source: 'https://www.timeout.com/',
        showMore: false,
    },
    {
        id: 5, 
        placeName: 'Watts Towers', 
        description: 'Italian-born tile-setter Simon Rodia began building the Watts Towers using nothing but scrap metal in the 1920s. Scaling the towers with a window-washer’s belt and bucket, he decorated them over the next three decades with consumer objects, such as green glass from bottles of 7-Up or Canada Dry and tiles from Malibu Pottery, as well as jewelry, marble and seashells. There are 17 of these intriguing structures, the tallest stretches nearly 100 feet into the sky. They still exude a kind of spectral beauty years after they were built.', 
        image: 'https://media.timeout.com/images/105496752/1372/1029/image.jpg', 
        source: 'https://www.timeout.com/',
        showMore: false,
    },
    {
        id: 6, 
        placeName: 'Universal Studios Hollywood', 
        description: 'The “Studios” part of this theme park’s name isn’t bluffing: Universal’s amusement park sits adjacent to its movie and TV studios, and the two even cross over a bit on the long-standing tram ride (its most recent addition includes the Western theme park from Nope). The rest of the standouts reside in two big-name thrills: Jurassic World: The Ride breathes some new life into a dino-filled favorite, while the Wizarding World of Harry Potter remains a highly-detailed, fantastical draw.', 
        image: 'https://media.timeout.com/images/103204698/1372/1029/image.jpg', 
        source: 'https://www.timeout.com/',
        showMore: false,
    },
    {
        id: 7, 
        placeName: 'Huntington Library', 
        description: 'If you’re in SoCal to take in as much culture as possible, you’ll be spoiled for choice at San Marino’s three-in-one attraction, the Huntington Library, Art Museum and Botanical Gardens. It’s an ingenious multi-purpose venue, which is home to an art gallery, a substantially stocked library and elaborate botanical gardens. The hilly Japanese garden, beautifully designed Chinese garden and cacti-filled desert garden are among the favorites. Take a whole day out to explore this fabulous Pasadena-adjacent place.', 
        image: 'https://media.timeout.com/images/105298563/1372/1029/image.jpg', 
        source: 'https://www.timeout.com/',
        showMore: false,
    },
    {
        id: 8, 
        placeName: 'the Broad', 
        description: 'Over half a decade in now and the arrival of the Broad still feels like a gamechanger thanks to the museum’s distinctive design, free admission and post-war art collection. Yayoi Kusama’s pair of Infinity Mirror Rooms in particular continue to pull in the crowds—one which transports viewers into a twinkling, pulsating starfield of LEDs (you can reserve a time slot), the other via smaller reflective chamber that you can pop your head into.', 
        image: 'https://media.timeout.com/images/105873340/1372/1029/image.jpg', 
        source: 'https://www.timeout.com/',
        showMore: false,
    },
    {
        id: 9, 
        placeName: 'The Getty Center', 
        description: 'The Getty Center is packed full of artistic masterpieces and enjoys an awe-inspiring hilltop location with incredible views of L.A. and a stunning central garden. Among the highlights hanging here are works by Rubens and Impressionists such as Renoir, Monet, Van Gogh and Cézanne—the lovely French decorative arts galleries are our personal favorites. If you want to rewind the clock a few millennia, head west to the museum’s predecessor, the Getty Villa. The Italian-style estate is stuffed with largely Greek and Roman antiquities, and its palatial courtyard is worth the trip alone.', 
        image: 'https://media.timeout.com/images/105777074/1372/1029/image.jpg', 
        source: 'https://www.timeout.com/',
        showMore: false,
    },
    {
        id: 10, 
        placeName: 'Malibu', 
        description: 'Put in the extra miles to venture north and west from Venice and Santa Monica and you’ll be rewarded with the most picturesque beaches in L.A. County. We couldn’t pick just one stretch of sand to visit in Malibu, so we’ll instead offer three: Point Dume for picnicking and sunbathing by an as-seen-on-TV scalable cliff, El Matador for sunsets among photogenic coves and outcrops and Leo Carrillo for secluded sand and an on-leash dog beach. If you’re hungry, we’ll recommend a trio of seafood spots, from east to west: superlative lobster rolls at Broad Street Oyster Co., excellent fish and chips at Malibu Seafood and fried goodness at Neptune’s Net.', 
        image: 'https://media.timeout.com/images/105150644/1372/1029/image.jpg', 
        source: 'https://www.timeout.com/',
        showMore: false,
    },
]
